-- Create the memories table if it doesn't exist
create table if not exists public.memories (
  id bigint generated by default as identity primary key,
  checkpoint_id bigint references public.checkpoints(id) on delete cascade,
  image_url text not null,
  note_him text,
  note_her text,
  order_index integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.memories enable row level security;

-- Drop existing policies if they exist (to avoid conflicts)
drop policy if exists "Enable read access for all users" on public.memories;
drop policy if exists "Enable insert for authenticated users only" on public.memories;
drop policy if exists "Enable update for authenticated users only" on public.memories;
drop policy if exists "Enable delete for authenticated users only" on public.memories;
drop policy if exists "Allow public read" on public.memories;
drop policy if exists "Allow public insert" on public.memories;
drop policy if exists "Allow public update" on public.memories;
drop policy if exists "Allow public delete" on public.memories;

-- Since this app uses localStorage auth (not Supabase Auth), 
-- we need to allow anon access for all operations
create policy "Allow public read" on public.memories for select using (true);
create policy "Allow public insert" on public.memories for insert with check (true);
create policy "Allow public update" on public.memories for update using (true);
create policy "Allow public delete" on public.memories for delete using (true);
